NEW-API/models/aluno.py
from config import db
from datetime import datetime

# criação da tabela de banco de dados
class Aluno(db.Model):
    __tablename__ = 'alunos'

    id = db.Column(db.Integer, primary_key=True)
    nome = db.Column(db.String(100), nullable=False)
    idade = db.Column(db.Integer, nullable=False)
    data_nascimento = db.Column(db.Date, nullable=False)
    nota_primeiro_semestre = db.Column(db.Float, nullable=False)
    nota_segundo_semestre = db.Column(db.Float, nullable=False)
    media_final = db.Column(db.Float, nullable=True)

    turma_id = db.Column(db.Integer, db.ForeignKey('turmas.id'), nullable=False)
    turma = db.relationship('Turma', back_populates='alunos')

    def __init__(self, nome, idade, data_nascimento, nota_primeiro_semestre, nota_segundo_semestre, turma_id):
        self.nome = nome
        self.idade = idade
        self.data_nascimento = data_nascimento
        self.nota_primeiro_semestre = nota_primeiro_semestre
        self.nota_segundo_semestre = nota_segundo_semestre
        self.media_final = (nota_primeiro_semestre + nota_segundo_semestre) / 2
        self.turma_id = turma_id

    def to_dict(self):
        return {
            'id': self.id,
            'nome': self.nome,
            'idade': self.idade,
            'data_nascimento': self.data_nascimento.strftime('%Y-%m-%d'),
            'nota_primeiro_semestre': self.nota_primeiro_semestre,
            'nota_segundo_semestre': self.nota_segundo_semestre,
            'media_final': self.media_final,
            'turma': self.turma.to_dict() if self.turma else None
    }

# criação de funções, para uso
class AlunoNaoEncontrado(Exception):
    pass

def aluno_por_id(id_aluno):
    aluno = Aluno.query.get(id_aluno)
    if not aluno:
        raise AlunoNaoEncontrado
    return aluno.to_dict()

def listar_alunos():
    alunos = Aluno.query.all()
    return [aluno.to_dict() for aluno in alunos]

def adicionar_aluno(aluno_data):
    data_nascimento = datetime.strptime(aluno_data['data_nascimento'], '%Y-%m-%d').date()
    novo_aluno = Aluno(
        nome=aluno_data['nome'],
        idade=int(aluno_data['idade']),
        data_nascimento=data_nascimento,
        nota_primeiro_semestre=float(aluno_data['nota_primeiro_semestre']),
        nota_segundo_semestre=float(aluno_data['nota_segundo_semestre']),
        turma_id=aluno_data['turma_id']
    )
    db.session.add(novo_aluno)
    db.session.commit()

def atualizar_aluno(id_aluno, novos_dados):
    aluno = Aluno.query.get(id_aluno)
    if not aluno:
        raise AlunoNaoEncontrado

    aluno.nome = novos_dados['nome']
    aluno.idade = int(novos_dados['idade'])
    aluno.data_nascimento = datetime.strptime(novos_dados['data_nascimento'], '%Y-%m-%d').date()
    aluno.nota_primeiro_semestre = float(novos_dados['nota_primeiro_semestre'])
    aluno.nota_segundo_semestre = float(novos_dados['nota_segundo_semestre'])
    aluno.media_final = (aluno.nota_primeiro_semestre + aluno.nota_segundo_semestre) / 2
    aluno.turma_id = int(novos_dados['turma_id'])

    db.session.commit()

def excluir_aluno(id_aluno):
    aluno = Aluno.query.get(id_aluno)
    if not aluno:
        raise AlunoNaoEncontrado

    db.session.delete(aluno)
    db.session.commit()

NEW-API/controllers/aluno_controller.py
from flask import request, jsonify
from models.aluno import Aluno, aluno_por_id, listar_alunos, adicionar_aluno, atualizar_aluno, excluir_aluno, AlunoNaoEncontrado
from models.turma import Turma
from config import db

# Tratamento de exeção no criar aluno
def create_aluno():
    data = request.get_json()
    turma_id = data.get('turma_id')
    if not turma_id or not Turma.query.get(turma_id):
        return jsonify({'message': 'Turma não encontrada!'}), 404
    adicionar_aluno(data)
    return jsonify({'message': 'Aluno criado com sucesso!'}), 201

# Tratamento de exeção no mostrar
def get_alunos():
    alunos = listar_alunos()
    return jsonify(alunos), 200

# Tratamento de exeção no exibor por id
def get_aluno(aluno_id):
    try:
        aluno = aluno_por_id(aluno_id)
        return jsonify(aluno), 200
    except AlunoNaoEncontrado:
        return jsonify({'message': 'Aluno não encontrado!'}), 404

# Tratamento de exeção no atualizar
def update_aluno(aluno_id):
    data = request.get_json()
    try:
        atualizar_aluno(aluno_id, data)
        return jsonify({'message': 'Aluno atualizado com sucesso!'}), 200
    except AlunoNaoEncontrado:
        return jsonify({'message': 'Aluno não encontrado!'}), 404

# Tratamento de exeção no criar aluno
def delete_aluno(aluno_id):
    try:
        excluir_aluno(aluno_id)
        return jsonify({'message': 'Aluno deletado com sucesso!'}), 200
    except AlunoNaoEncontrado:
        return jsonify({'message': 'Aluno não encontrado!'}), 404

NEW-API/routes/aluno_routes.py
from flask import Blueprint, request, render_template, redirect, url_for, jsonify
from models.aluno import AlunoNaoEncontrado, listar_alunos, aluno_por_id, adicionar_aluno, atualizar_aluno, excluir_aluno

alunos_bp = Blueprint('alunos', __name__)


# mostrar
@alunos_bp.route('/alunos', methods=['GET'])
def get_alunos():
    alunos = listar_alunos()
    return render_template("/alunos/alunos.html", alunos=alunos)

# mostrar por id
@alunos_bp.route('/alunos/<int:id_aluno>', methods=['GET'])
def get_aluno(id_aluno):
    try:
        aluno = aluno_por_id(id_aluno)
        return render_template('/alunos/aluno_id.html', aluno=aluno)
    except AlunoNaoEncontrado:
        return jsonify({'message': 'Aluno não encontrado'}), 404

# criar
@alunos_bp.route('/alunos/criar', methods=['GET'])
def adicionar_aluno_page():
    return render_template('/alunos/criar_aluno.html')

@alunos_bp.route('/alunos', methods=['POST'])
def create_aluno():
    novo_aluno = {
        'nome': request.form['nome'],
        'idade': int(request.form['idade']),
        'data_nascimento': request.form['data_nascimento'],
        'nota_primeiro_semestre': float(request.form['nota_primeiro_semestre']),
        'nota_segundo_semestre': float(request.form['nota_segundo_semestre']),
        'media_final': float(request.form['media_final']),
        'turma_id': int(request.form['turma_id'])  
    }
    adicionar_aluno(novo_aluno)
    return redirect(url_for('alunos.get_alunos'))

@alunos_bp.route('/alunos/atualizar/<int:id_aluno>', methods=['GET'])
def editar_aluno_page(id_aluno):
    try:
        aluno = aluno_por_id(id_aluno)
        return render_template('/alunos/aluno_update.html', aluno=aluno)
    except AlunoNaoEncontrado:
        return jsonify({'message': 'Aluno não encontrado'}), 404

@alunos_bp.route('/alunos/<int:id_aluno>', methods=['POST'])
def update_aluno(id_aluno):
    novos_dados = {
        'nome': request.form['nome'],
        'idade': int(request.form['idade']),
        'data_nascimento': request.form['data_nascimento'],
        'nota_primeiro_semestre': float(request.form['nota_primeiro_semestre']),
        'nota_segundo_semestre': float(request.form['nota_segundo_semestre']),
        'media_final': float(request.form['media_final']),
        'turma_id': int(request.form['turma_id']) 
    }
    try:
        atualizar_aluno(id_aluno, novos_dados)
        return redirect(url_for('alunos.get_aluno', id_aluno=id_aluno))
    except AlunoNaoEncontrado:
        return jsonify({'message': 'Aluno não encontrado'}), 404

@alunos_bp.route('/alunos/delete/<int:id_aluno>', methods=['POST'])
def delete_aluno(id_aluno):
    try:
        excluir_aluno(id_aluno)
        return redirect(url_for('alunos.get_alunos'))
    except AlunoNaoEncontrado:
        return jsonify({'message': 'Aluno não encontrado'}), 404


NEW-API/templates/alunos/aluno_id.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Detalhes do Aluno</title>
</head>
<body>
  <h1>Detalhes do Aluno</h1>
  <br><p><strong>ID:</strong> {{ aluno.id }}</p></br>

  <br><p><strong>Nome:</strong> {{ aluno.nome }}</p></br>

  <br><p><strong>Idade:</strong> {{ aluno.idade }}</p></br>

  <br><p><strong>Turma:</strong> {{ aluno.turma.descricao if aluno.turma else 'Sem turma' }}</p></br>

  <br><p><strong>Data de Nascimento:</strong> {{ aluno.data_nascimento }}</p><br>

  <br><p><strong>Nota do Primeiro Semestre:</strong> {{ aluno.nota_primeiro_semestre }}</p></br>

  <br><p><strong>Nota do Segundo Semestre:</strong> {{ aluno.nota_segundo_semestre }}</p></br>

  <br><p><strong>Média Final:</strong> {{ aluno.media_final }}</p></br>

  <br><form action="{{ url_for('alunos.delete_aluno', id_aluno=aluno.id) }}" method="POST"></br>
    
    <button type="submit">Excluir Aluno</button>
  </form>
  <a href="{{ url_for('alunos.get_alunos') }}">Voltar para a lista de alunos</a>
</body>
</html>

NEW-API/templates/alunos/aluno_update.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Editar Aluno</title>
</head>
<body>
  <h1>Editar Aluno</h1>
  <form action="{{ url_for('alunos.update_aluno', id_aluno=aluno.id) }}" method="POST">
    <label for="nome">Nome:</label><br>
    <input type="text" id="nome" name="nome" value="{{ aluno.nome }}"><br>

    <label for="idade">Idade:</label><br>
    <input type="number" id="idade" name="idade" value="{{ aluno.idade }}"><br>

    <label for="data_nascimento">Data de Nascimento:</label><br>
    <input type="date" id="data_nascimento" name="data_nascimento" value="{{ aluno.data_nascimento }}"><br>

    <label for="nota_primeiro_semestre">Nota Primeiro Semestre:</label><br>
    <input type="number" step="0.1" id="nota_primeiro_semestre" name="nota_primeiro_semestre" value="{{ aluno.nota_primeiro_semestre }}"><br>

    <label for="nota_segundo_semestre">Nota Segundo Semestre:</label><br>
    <input type="number" step="0.1" id="nota_segundo_semestre" name="nota_segundo_semestre" value="{{ aluno.nota_segundo_semestre }}"><br>

    <label for="media_final">Média Final:</label><br>
    <input type="number" step="0.1" id="media_final" name="media_final" value="{{ aluno.media_final }}"><br>

    <label for="turma_id">Turma ID:</label><br>
    <input type="number" id="turma_id" name="turma_id" value="{{ aluno.turma.id }}"><br>

    <input type="submit" value="Atualizar Aluno">
  </form>
  <a href="{{ url_for('alunos.get_alunos') }}">Voltar para a lista de alunos</a>
</body>
</html>


NEW-API/templates/alunos/alunos.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Lista de Alunos</title>

</head>
<body>
  <h1>Lista de Alunos</h1>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Nome</th>
        
      </tr>
    </thead>
    <tbody>
      {% for aluno in alunos %}
      <tr>
        <td>{{ aluno.id }}</td>
        <td><a href="{{ url_for('alunos.get_aluno', id_aluno=aluno.id) }}">{{ aluno.nome }}</a></td>
        
        <td>
          <a href="{{ url_for('alunos.editar_aluno_page', id_aluno=aluno.id) }}">Editar</a>
          <form action="{{ url_for('alunos.delete_aluno', id_aluno=aluno.id) }}" method="POST" style="display:inline;">
            <button type="submit">Excluir</button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <a href="{{ url_for('alunos.adicionar_aluno_page') }}">Adicionar Novo Aluno</a>
</body>
</html>


NEW-API/templates/alunos/criar_aluno.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Adicionar Aluno</title>
</head>
<body>
  <h1>Adicionar Aluno</h1>
  <form action="{{ url_for('alunos.create_aluno') }}" method="post">
    <label for="nome">Nome:</label><br>
    <input type="text" id="nome" name="nome"><br>

    <label for="idade">Idade:</label><br>
    <input type="number" id="idade" name="idade"><br>

    <label for="data_nascimento">Data de Nascimento:</label><br>
    <input type="date" id="data_nascimento" name="data_nascimento"><br>

    <label for="nota_primeiro_semestre">Nota Primeiro Semestre:</label><br>
    <input type="number" step="0.1" id="nota_primeiro_semestre" name="nota_primeiro_semestre"><br>

    <label for="nota_segundo_semestre">Nota Segundo Semestre:</label><br>
    <input type="number" step="0.1" id="nota_segundo_semestre" name="nota_segundo_semestre"><br>

    <label for="media_final">Média Final:</label><br>
    <input type="number" step="0.1" id="media_final" name="media_final"><br>

    <label for="turma_id">Turma ID:</label><br>
    <input type="number" id="turma_id" name="turma_id"><br>

    <input type="submit" value="Adicionar Aluno">
  </form>
  <a href="{{ url_for('alunos.get_alunos') }}">Voltar para a lista de alunos</a>
</body>
</html>

